project:
  type: website
  output-dir: docs

website:
  title: "Orderly Qwilting"
  description: "Quarto blog to capture what I learn."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - text: Archive
        href: archive.qmd
      - icon: github
        href: https://github.com/orderlyquant
format:
  html:
    theme: theme.scss

execute:
  echo: false  # true, false, fenced
  message: false
  warning: false



